#!/bin/bash
wget https://cmake.org/files/v3.15/cmake-3.15.4-Linux-x86_64.sh -q && mkdir /tmp/cmake &&  printf "y\nn\n" | sh cmake-3.15.4-Linux-x86_64.sh --prefix=/tmp/cmake > /dev/null && rm -rf cmake-3.15.4-Linux-x86_64.sh
export PATH=/tmp/cmake/bin:$PATH

export NODE_OPTIONS=--max-old-space-size=32768

jupyter lab build --dev-build=False --minimize=True

jupyter serverextension enable --py jupyterlab
jupyter serverextension enable --py jupyterlab_iframe
jupyter serverextension enable --py nbresuse

config="c.JupyterLabIFrame.welcome = 'local://binder/landing.html'"

mkdir -p ~/.jupyter
echo -e $config > ~/.jupyter/jupyter_notebook_config.py
